name: pipeline 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-suite:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Install dependencies
      run: make linux_env

    - name: update submodules
      run: git submodule update --init --recursive

    - name: Start Xvfb
      run: Xvfb :99 & export DISPLAY=:99

    - name: Run test suite
      run: |
        export DISPLAY=:99
        make test 
        lcov --list test/build/coverage.info

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: test/build/coverage.info
        fail_ci_if_error: true